language: android

android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project // check build-tools-version in sdk manager
    - build-tools-28.0.3

    # The SDK version used to compile your project // build.gradle(Module.app) targetsdk version
    - android-27

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script: ./gradlew build